account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^edit/$', views.edit, name='edit'),
]

blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^posts/$', views.PostListView.as_view(), name='post_list'),
    url(r'^posts/top/$', views.TopPostListView.as_view(), name='post_top'),
    url(r'^posts/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
        r'(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^posts/rate/$', views.post_rate, name='post_rate'),
    url(r'^posts/add/$', views.post_add, name='post_add'),
    url(r'^categories/$', views.CategoryListView.as_view(), name='category_list'),
    url(r'^categories/(?P<category>[-\w]+)/$', views.category_detail, name='category_detail'),
]

choco_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static  import static 

from blog import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" 
				href="{% static 'css/main.css' %}">	
	{% load bootstrap3 %}
	{% bootstrap_css %}		
</head>
<body id="wrapper">
<div>
	{% bootstrap_messages %}

	{% include 'navbar.html' %}
	<div class="container">			
		{% block content %}
		{% endblock %}
	</div>
</div>

<script type="text/javascript" 
				src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" 
				src="{% static 'js/main.js' %}"></script>				
{% bootstrap_javascript %}	
{% block scripts %}
{% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'post_list' %}">ChocoBlog</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">      			
		  	<li>
		  		<a href="{% url 'blog:category_list' %}">Categories</a>
		  	</li>
		  	<li>
		  		<a href="{% url 'blog:post_list' %}">Posts</a>
		  	</li>		  	
				<li>
					<a href="{% url 'blog:post_top' %}">
						Top posts	
					</a>
				</li>
		  	<li>
					<a href="{% url 'blog:post_add' %}">Add New Post</a>
				</li>	
    	</ul>

    <ul class="nav navbar-nav navbar-right">      
      {% if user.is_authenticated %}
      	<li>
      		<a href="{% url 'account:profile' %}">Profile</a>
      	</li>
      	<li>
      		<a href="{% url 'account:logout' %}">Log Out</a>
      	</li>
      {% else %}
      	<li>
      		<a href="{% url 'account:login' %}">Log In</a>
      	</li>
      	<li>
      		<a href="{% url 'account:register' %}">Register</a>
      	</li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/sidebar.html
<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
		<li class="sidebar-brand">
			<a href="#">Menu</a>
		</li>
	</ul>
</div>	